openapi: 3.2.0
info:
  title: Weavr Webhook Manual Transactions API
  description: For Verification, create a base64 hash using HmacSHA256 using Published-Timestamp header as message and your API key as secret. The result should match the Signature header.
  contact:
    name: Weavr
    url: https://weavr.io
  version: v2
  x-logo:
    url: https://storage.googleapis.com/weavr-cdn/weavr_logo-new.png
    backgroundColor: '#FFFFFF'
    altText: Weavr
servers:
- url: '""'
tags:
- name: Manual Transactions
paths: {}
webhooks:
  /manual_transactions/watch:
    post:
      tags:
      - Manual Transactions
      summary: Manual transaction
      description: Notification that a manual transaction has been processed.
      operationId: manual_transactions_watch
      parameters:
      - $ref: '#/components/parameters/call-ref'
      - $ref: '#/components/parameters/published-timestamp'
      - $ref: '#/components/parameters/signature'
      - $ref: '#/components/parameters/signature-v2'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualTransactionEvent'
        required: true
      responses:
        '204':
          description: Success - No Content
components:
  schemas:
    ManualTransactionEvent:
      required:
      - targetInstrument
      - transactionId
      - transactionTimestamp
      type: object
      properties:
        transactionId:
          type: string
          pattern: ^[0-9]+$
          description: Id of the transaction.
        targetInstrument:
          $ref: '#/components/schemas/InstrumentId'
          description: Id of the instrument on which the manual operation was performed.
        availableBalanceAdjustment:
          type: string
          pattern: ^[0-9]+$
          description: The amount credited or debited on the available balance of the instrument.
        actualBalanceAdjustment:
          type: string
          pattern: ^[0-9]+$
          description: The amount credited or debited on the actual balance of the instrument.
        transactionTimestamp:
          type: string
          pattern: ^[0-9]+$
          description: The timestamp when the transaction was processed by the system, expressed in Epoch timestamp using millisecond precision.
        owner:
          $ref: '#/components/schemas/StringWrappedTypeId'
    StringWrappedTypeId:
      required:
      - type
      - id
      type: object
      properties:
        type:
          maxLength: 50
          pattern: ^[a-zA-Z0-9_-]+$
          type: string
        id:
          type: string
          pattern: ^[0-9]+$
    InstrumentType:
      type: string
      enum:
      - managed_cards
      - managed_accounts
    Id:
      type: string
      pattern: ^[0-9]+$
    InstrumentId:
      required:
      - id
      - type
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        type:
          $ref: '#/components/schemas/InstrumentType'
  parameters:
    signature:
      name: signature
      in: header
      description: The signature to verify the authenticity of this request.  This is the base64 hash (HmacSHA256) of the `published-timestamp` using your API key.
      required: true
      style: simple
      explode: false
      deprecated: true
      schema:
        type: string
    signature-v2:
      name: signature-v2
      in: header
      description: The signature to verify the authenticity of this request.  This is the base64 hash (HmacSHA256) of the `call-ref + payload + published-timestamp` using your API key.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    call-ref:
      description: A call reference generated by the caller and unique to the caller to provide correlation between the caller and system with a maximum length of 255
      in: header
      name: call-ref
      required: false
      schema:
        type: string
    published-timestamp:
      name: published-timestamp
      in: header
      description: The timestamp, expressed in Epoch timestamp using millisecond precision, when this event was published.
      required: true
      style: simple
      explode: false
      schema:
        type: integer
        format: int64
x-tagGroups:
- name: Webhooks
  tags:
  - Corporates
  - Consumers
  - Managed Cards
  - Managed Accounts
  - Transfers
  - Sends
  - Outgoing Wire Transfers
  - Correspondent Bank Transfers
  - Manual Transactions
  - Fees
  - Login
  - Stepup
  - Authentication Factors
  - Trusted Payees
  - Bulk Operations
  - Authorised Users
